# Generated by Django 4.0.5 on 2022-12-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranking',
            new_name='RankingTo10',
        ),
    ]
