# Generated by Django 4.0.5 on 2022-12-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ranking_rankingto10'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingTo50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerName', models.CharField(max_length=24)),
                ('Score', models.IntegerField()),
            ],
        ),
    ]
