# Generated by Django 4.1.5 on 2023-01-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_rankingto10_playername_and_more"),
    ]

    operations = []
